export const logoPopupsData = [
  {
    logo: "/images/unicef-logo.png",
    popupImage: "/images/unicef-popup-img.png",
    title: "Unicef",
    description: "Funding cuts are slashing children's lifelines",
    href: "",
    logoWidth: 130.86,
    logoHeight: 42.73,
  },
  {
    logo: "/images/alert-logo.png",
    popupImage: "/images/alert-popup-img.png",
    title: "Alert Force",
    description: "The Health & Safety Training People",
    href: "",
    logoWidth: 155.86,
    logoHeight: 40.02,
  },
  {
    logo: "/images/ndifo-logo.png",
    popupImage: "/images/ndifo-popup-img.png",
    title: "Ndifo Safari",
    description: "Experience The Natural & Cultural Wonders Of East Africa",
    href: "",
    logoWidth: 96.31,
    logoHeight: 69.84,
  },
  {
    logo: "/images/little-logo.png",
    popupImage: "/images/little-popup-img.png",
    title: "Little Astronauts",
    description: "Recharge while they explore at Little astronauts!",
    href: "",
    logoWidth: 142.85,
    logoHeight: 41.19,
  },
  {
    logo: "/images/new-logo.png",
    popupImage: "/images/new-popup-img.png",
    title: "New Compass",
    description: "The next generation of 3D geospatial analysis",
    href: "",
    logoWidth: 147.97,
    logoHeight: 25.74,
  },
  {
    logo: "/images/ayoa-logo.png",
    popupImage: "/images/ayoa-popup-img.png",
    title: "AYOA",
    description: "#1 AI-powered mind mapping tool",
    href: "",
    logoWidth: 128.12,
    logoHeight: 39.7,
  },
  {
    logo: "/images/anthony-logo.png",
    popupImage: "/images/anthony-popup-img.png",
    title: "Anthony Walker",
    description: "Funding cuts are slashing children's lifelines",
    href: "",
    logoWidth: 135.69,
    logoHeight: 55.31,
  },
];
